### PR TITLE
feat: handle removed attributes

### PR DESCRIPTION
**Pull request by smomin**
- add logic to handle removed attributes from firestore record.
- add unit test for the new logic

### CODE REVIEW

**Comment by saifxx** [comment]
When this update will available in firebase extensions?

**Comment by Haroenv** [comment]
this makes sense to me, but why aren't we always using save object?

**Review by Haroenv — APPROVED** [review]
good workaround for now, and is tested

**Comment by smomin** [comment]
@Haroenv I am solving for race condition which is described here, https://github.com/algolia/firestore-algolia-search/issues/32.  Now, using NodeJS, the race condition can be somewhat frequent to rare.  The reason I did not use saveObject is because it does not provide versioning to protect against race conditions.  The partialUpdate method has version which is helping to prevent the race condition.  Or, I can implement an extra Firebase record update before sending it to Algolia but this will incurr a read hit.

**Pull request merged**
